"""
Genres as narrated live-coding performances.

Each genre is a set of lanes plus a *script of edits*: bring a part in, chain an
effect onto a line that is already playing, nudge one number, solo something,
take a part away. The build order and the kinds of edit follow Switch Angel's
narrated Strudel sets, where almost every move is a small change to a line that
is already sounding:

    "tame with an acid slider" · "duck it with our kick" · "lower the depth of
    the duck to 0.8" · "lower the decay" · "destroy the bass with diode
    distortion" · "FM the bass with time" · "drop the bass to F1" · "add 30
    semitones" · "random detune for more power" · "isolate the lead" ·
    "turn our hi-hats into an infinite riser" · "bring in the angels"

Two functions in those videos are her own and do not exist in Strudel:
`trancegate` is written here as `tremolosync`/`tremolodepth`/`tremoloshape`,
and `rlpf(x)` as `lpf(x).lpq(n)`.

Everything else is verified present in the bundle before use —
tools/maintenance/verify_strudel_patterns.py plays every step of every script
and measures the audio, because a pattern Strudel cannot parse fails silently.
"""

from utils.audio.performance import ADD, CLEAR, DROP, FX, SET, SOLO

# Slider ranges are exposed so a human can ride them in the editor while Kaia
# plays; she writes slider(x, lo, hi) and only ever changes x.
GENRES: dict[str, dict] = {
    'trance': {
        "bpm": '~138', "cpm": '138/4',
        "blurb": 'supersaw trance: acid bass, ducked gates, riser, breakdown',
        "lanes": {
            'kick': 's("bd*4").gain(0.95).o(1)._scope()',
            'bass': 'n("<0>*16").scale("g2:minor").s("supersaw").o(3)',
            'hats': 's("hh*8").gain(0.22).o(2)',
            'clap': 's("~ cp").gain(0.4).room(0.3).o(2)',
            'lead': 'n("<0 4 0 9 7>*16").scale("g4:minor").s("supersaw").o(4)',
            'pad': 'n("<0,3,7 -2,2,5 -4,0,3 0,3,7>*2").scale("g3:minor").s("supersaw").o(5)',
            'riser': 's("hh*16").gain(0.14).o(6)',
            'vox': 's("speech:3").scrub(rand.seg(16).rib(4,2)).gain(0.34).o(7)',
        },
        "script": [
            {"op": ADD, "lane": 'kick', "seconds": 18, "say": 'kick drum, four on the floor'},
            {"op": ADD, "lane": 'bass', "seconds": 16, "say": 'next, bass'},
            {"op": FX, "lane": 'bass', "arg": '.lpf(slider(0.35,0,1).range(180,2600)).lpq(8)', "seconds": 18, "say": 'tame it with an acid slider'},
            {"op": FX, "lane": 'bass', "arg": '.attack(0.01).decay(0.16).sustain(0.08).release(0.18)', "seconds": 14, "say": 'tighten the envelope'},
            {"op": FX, "lane": 'bass', "arg": '.duck("1").duckdepth(0.5).duckattack(0.14)', "seconds": 16, "say": 'duck it with our kick'},
            {"op": SET, "lane": 'bass', "arg": 'duckdepth', "value": '0.8', "seconds": 14, "say": 'lower the depth of the duck to 0.8'},
            {"op": FX, "lane": 'bass', "arg": '.detune(rand)', "seconds": 14, "say": 'random detune for more power'},
            {"op": ADD, "lane": 'hats', "seconds": 16, "say": 'white noise hi-hats'},
            {"op": FX, "lane": 'hats', "arg": '.dec(tri.range(0.03,0.14).slow(7))', "seconds": 16, "say": 'decay modulated with a triangle wave'},
            {"op": ADD, "lane": 'lead', "seconds": 20, "say": 'our lead will be a supersaw'},
            {"op": FX, "lane": 'lead', "arg": '.lpf(slider(0.5,0,1).range(500,5200)).lpq(2)', "seconds": 16, "say": 'acid slider on the lead'},
            {"op": FX, "lane": 'lead', "arg": '.attack(0.01).decay(0.2).sustain(0.15).release(0.8)', "seconds": 14, "say": 'give it a tail'},
            {"op": FX, "lane": 'lead', "arg": '.delay(0.4).delaytime(0.1875).delayfeedback(0.55)', "seconds": 16, "say": 'we need more power with delay'},
            {"op": FX, "lane": 'lead', "arg": '.pan(rand)', "seconds": 14, "say": "let's make it swirl with random panning"},
            {"op": ADD, "lane": 'clap', "seconds": 16, "say": 'clap, to increase the harmonic tilt'},
            {"op": ADD, "lane": 'pad', "seconds": 18, "say": 'bring the pad underneath'},
            {"op": FX, "lane": 'pad', "arg": '.attack(1.2).release(3).lpf(perlin.range(400,1800)).lpq(0)', "seconds": 16, "say": 'slow it right down'},
            {"op": FX, "lane": 'pad', "arg": '.duck("1").duckdepth(0.55)', "seconds": 16, "say": 'duck the pad too'},
            {"op": SET, "lane": 'lead', "arg": 'lpq', "value": '6', "seconds": 14, "say": 'increase the power of our filter'},
            {"op": SOLO, "lane": 'lead', "seconds": 22, "say": 'isolate the lead'},
            {"op": CLEAR, "seconds": 16, "say": 'and bring it all back'},
            {"op": DROP, "lane": 'kick', "seconds": 20, "say": 'breakdown — drop the kick'},
            {"op": DROP, "lane": 'hats', "seconds": 18, "say": 'just the pad and the lead'},
            {"op": ADD, "lane": 'riser', "seconds": 16, "say": 'an infinite riser'},
            {"op": FX, "lane": 'riser', "arg": '.dec(0.08).fm(time).fmh(time)', "seconds": 16, "say": 'FM it with time'},
            {"op": ADD, "lane": 'kick', "seconds": 20, "say": 'bring our kick back in'},
            {"op": ADD, "lane": 'hats', "seconds": 18, "say": 'and the hats'},
            {"op": FX, "lane": 'lead', "arg": '.fm(0.5).fmwave("brown")', "seconds": 18, "say": 'FM the supersaw with noise for more chaos'},
            {"op": SET, "lane": 'bass', "arg": 'lpq', "value": '12', "seconds": 16, "say": 'more power on the bass'},
            {"op": DROP, "lane": 'riser', "seconds": 22, "say": 'let it ride'},
            {"op": ADD, "lane": 'vox', "seconds": 18, "say": "bring in the angels"},
            {"op": FX, "lane": 'vox', "arg": '.delay(0.5).delaytime(0.375).delayfeedback(0.5).pan(rand)', "seconds": 16, "say": 'scrub it like a tape loop'},
            {"op": DROP, "lane": 'lead', "seconds": 18, "say": 'take the lead out'},
            {"op": DROP, "lane": 'clap', "seconds": 16, "say": 'and out'},
        ],
    },

    'house': {
        "bpm": '~124', "cpm": '124/4',
        "blurb": 'deep house: four-to-the-floor, off-beat hats, ducked rhodes chords',
        "lanes": {
            'kick': 's("bd*4").gain(0.9).o(1)._scope()',
            'hats': 's("[~ hh]*4").gain(0.3).o(2)',
            'shaker': 's("hh:2*8").gain(0.1).degradeBy(0.3).pan(rand).o(2)',
            'snare': 's("~ sd").gain(0.4).room(0.25).o(2)',
            'bass': 'n("<0 0 -5 -3>*8").scale("c2:minor").s("sawtooth").o(3)',
            'chords': 'n("<0,2,4 0,2,4 -3,-1,1 <-5,-3,-1 1,3,5>>*4").scale("c4:minor").s("supersaw").o(4)',
            'top': 'n("<12 10 15 12>*8").scale("c5:minor").s("triangle").o(5)',
            'vox': 's("speech:1").chop(8).gain(0.3).o(7)',
        },
        "script": [
            {"op": ADD, "lane": 'kick', "seconds": 18, "say": 'kick drum, four on the floor'},
            {"op": ADD, "lane": 'hats', "seconds": 16, "say": 'off-beat hats'},
            {"op": ADD, "lane": 'bass', "seconds": 16, "say": 'bass underneath'},
            {"op": FX, "lane": 'bass', "arg": '.lpf(slider(0.3,0,1).range(160,900)).lpq(3)', "seconds": 16, "say": 'filter the bass'},
            {"op": FX, "lane": 'bass', "arg": '.attack(0.01).decay(0.18).sustain(0.1).release(0.2)', "seconds": 14, "say": 'tighten it'},
            {"op": FX, "lane": 'bass', "arg": '.duck("1").duckdepth(0.7).duckattack(0.12)', "seconds": 16, "say": 'duck it with the kick'},
            {"op": ADD, "lane": 'snare', "seconds": 16, "say": 'snare on the two'},
            {"op": ADD, "lane": 'chords', "seconds": 18, "say": 'rhodes chords'},
            {"op": FX, "lane": 'chords', "arg": '.attack(0.02).decay(0.5).sustain(0.2).release(1.2)', "seconds": 14, "say": 'let them ring'},
            {"op": FX, "lane": 'chords', "arg": '.lpf(slider(0.45,0,1).range(500,2400)).lpq(0)', "seconds": 16, "say": 'open them up'},
            {"op": FX, "lane": 'chords', "arg": '.room(0.45).delay(0.22).delaytime(0.375)', "seconds": 16, "say": 'space and delay'},
            {"op": FX, "lane": 'chords', "arg": '.duck("1").duckdepth(0.6)', "seconds": 16, "say": 'duck the chords'},
            {"op": ADD, "lane": 'shaker', "seconds": 16, "say": 'shaker on top'},
            {"op": ADD, "lane": 'top', "seconds": 18, "say": 'a sparkle up high'},
            {"op": FX, "lane": 'top', "arg": '.degradeBy(0.72).attack(0.01).release(1.6).pan(rand).room(0.7).delay(0.45)', "seconds": 18, "say": 'scatter it'},
            {"op": SOLO, "lane": 'chords', "seconds": 20, "say": 'isolate the chords'},
            {"op": CLEAR, "seconds": 18, "say": 'everything back'},
            {"op": DROP, "lane": 'kick', "seconds": 18, "say": 'breakdown'},
            {"op": DROP, "lane": 'hats', "seconds": 16, "say": 'let the chords breathe'},
            {"op": SET, "lane": 'chords', "arg": 'duckdepth', "value": '0.2', "seconds": 14, "say": 'ease off the ducking'},
            {"op": ADD, "lane": 'kick', "seconds": 18, "say": 'kick returns'},
            {"op": SET, "lane": 'chords', "arg": 'duckdepth', "value": '0.6', "seconds": 14, "say": 'and pump it again'},
            {"op": ADD, "lane": 'hats', "seconds": 20, "say": 'full groove'},
            {"op": SET, "lane": 'bass', "arg": 'lpq', "value": '7', "seconds": 16, "say": 'more bite on the bass'},
            {"op": ADD, "lane": 'vox', "seconds": 18, "say": "add a vocal chop"},
            {"op": FX, "lane": 'vox', "arg": '.rev().delay(0.4).delaytime(0.5).room(0.5).pan(rand)', "seconds": 16, "say": 'reverse and echo the vocal'},
            {"op": DROP, "lane": 'top', "seconds": 18, "say": 'thin it out'},
            {"op": DROP, "lane": 'shaker', "seconds": 16, "say": 'and out'},
        ],
    },

    'techno': {
        "bpm": '~134', "cpm": '134/4',
        "blurb": 'driving techno: acid line, hard kick, long filter builds',
        "lanes": {
            'kick': 's("bd*4").gain(1.0).o(1)._scope()',
            'hats': 's("[~ hh]*4").gain(0.26).o(2)',
            'ticks': 's("hh:3*8").gain(0.13).pan(rand).o(2)',
            'clap': 's("~ ~ cp ~").gain(0.35).room(0.35).o(2)',
            'acid': 'n("{0 0 3 0 5 0 7 3}%16").scale("a2:minor").s("sawtooth").o(3)',
            'sub': 'n("<0>*8").scale("a1:minor").s("supersaw").o(4)',
            'pad': 'n("<0,3,7 -2,2,5>*2").scale("a4:minor").s("supersaw").o(5)',
            'vox': 's("numbers*2").chop(4).gain(0.26).o(7)',
        },
        "script": [
            {"op": ADD, "lane": 'kick', "seconds": 20, "say": 'kick, four on the floor'},
            {"op": ADD, "lane": 'sub', "seconds": 16, "say": 'sub underneath'},
            {"op": FX, "lane": 'sub', "arg": '.detune(rand).attack(0.01).decay(0.3).release(0.25).lpf(220).lpq(0)', "seconds": 16, "say": 'keep it low'},
            {"op": FX, "lane": 'sub', "arg": '.duck("1").duckdepth(0.65)', "seconds": 16, "say": 'duck it'},
            {"op": ADD, "lane": 'hats', "seconds": 16, "say": 'hats'},
            {"op": ADD, "lane": 'acid', "seconds": 18, "say": 'the acid line'},
            {"op": FX, "lane": 'acid', "arg": '.attack(0.005).decay(0.1).sustain(0.04).release(0.16)', "seconds": 14, "say": 'short and snappy'},
            {"op": FX, "lane": 'acid', "arg": '.lpf(slider(0.28,0,1).range(220,3200)).lpq(9)', "seconds": 18, "say": 'tame it with an acid slider'},
            {"op": FX, "lane": 'acid', "arg": '.delay(0.28).delaytime(0.1875).delayfeedback(0.5)', "seconds": 16, "say": 'delay for power'},
            {"op": FX, "lane": 'acid', "arg": '.duck("1").duckdepth(0.7).duckattack(0.1)', "seconds": 16, "say": 'duck against the kick'},
            {"op": ADD, "lane": 'clap', "seconds": 16, "say": 'clap'},
            {"op": ADD, "lane": 'ticks', "seconds": 16, "say": 'ticks on top'},
            {"op": SET, "lane": 'acid', "arg": 'lpq', "value": '13', "seconds": 16, "say": 'more resonance'},
            {"op": FX, "lane": 'acid', "arg": '.distort(1.6)', "seconds": 18, "say": 'destroy it with distortion'},
            {"op": SOLO, "lane": 'acid', "seconds": 20, "say": 'isolate the acid'},
            {"op": CLEAR, "seconds": 18, "say": 'all back in'},
            {"op": DROP, "lane": 'kick', "seconds": 18, "say": 'breakdown'},
            {"op": ADD, "lane": 'pad', "seconds": 18, "say": 'a pad in the gap'},
            {"op": FX, "lane": 'pad', "arg": '.detune(rand).attack(1.5).release(4).lpf(perlin.range(500,2000)).lpq(0).room(0.8)', "seconds": 18, "say": 'wide and slow'},
            {"op": ADD, "lane": 'kick', "seconds": 20, "say": 'kick back'},
            {"op": SET, "lane": 'acid', "arg": 'lpq', "value": '6', "seconds": 16, "say": 'pull the resonance back'},
            {"op": FX, "lane": 'acid', "arg": '.fm(0.4).fmwave("brown")', "seconds": 18, "say": 'FM it with noise'},
            {"op": ADD, "lane": 'vox', "seconds": 16, "say": "a voice in the machine"},
            {"op": FX, "lane": 'vox', "arg": '.speed(0.8).delay(0.5).delaytime(0.1875).pan(rand)', "seconds": 16, "say": 'pitch it down and delay it'},
            {"op": DROP, "lane": 'ticks', "seconds": 18, "say": 'thin out'},
            {"op": DROP, "lane": 'clap', "seconds": 16, "say": 'and out'},
        ],
    },

    'drumnbass': {
        "bpm": '~174', "cpm": '174/4',
        "blurb": 'fast breakbeat, deep sub, atmospheric pads',
        "lanes": {
            'pad': 'n("<0,3,7 0,3,7 -2,2,5 <-4,0,3 0,5,8>>*4").scale("d4:minor").s("supersaw").o(5)',
            'sub': 'n("<0 0 5 3>*4").scale("d1:minor").s("sine").o(3)',
            'kick': 's("bd ~ ~ ~ ~ ~ bd ~").gain(0.9).o(1)._scope()',
            'snare': 's("~ ~ ~ ~ sd ~ ~ ~").gain(0.62).room(0.2).o(2)',
            'hats': 's("hh*8").gain(0.18).pan(rand).o(2)',
            'ghost': 's("hh:4*16").gain(0.1).degradeBy(0.4).o(2)',
            'bells': 'n("<12 15 19 17>*8").scale("d5:minor").s("triangle").o(6)',
            'vox': 's("speech:5").scrub(rand.seg(8).rib(2,2)).gain(0.3).o(7)',
        },
        "script": [
            {"op": ADD, "lane": 'pad', "seconds": 20, "say": 'open on a pad'},
            {"op": FX, "lane": 'pad', "arg": '.detune(rand.range(0,0.35)).attack(0.8).release(3).lpf(perlin.range(500,1900)).lpq(0).room(0.85)', "seconds": 18, "say": 'wide and slow'},
            {"op": ADD, "lane": 'sub', "seconds": 16, "say": 'sub bass'},
            {"op": FX, "lane": 'sub', "arg": '.attack(0.01).decay(0.6).sustain(0.4).release(0.35).lpf(170)', "seconds": 14, "say": 'keep it deep'},
            {"op": ADD, "lane": 'kick', "seconds": 16, "say": 'the break'},
            {"op": ADD, "lane": 'snare', "seconds": 16, "say": 'snare'},
            {"op": FX, "lane": 'sub', "arg": '.duck("1").duckdepth(0.5).duckattack(0.08)', "seconds": 16, "say": 'duck the sub'},
            {"op": ADD, "lane": 'hats', "seconds": 18, "say": 'hats'},
            {"op": ADD, "lane": 'ghost', "seconds": 16, "say": 'ghost notes'},
            {"op": ADD, "lane": 'bells', "seconds": 18, "say": 'bells over the top'},
            {"op": FX, "lane": 'bells', "arg": '.degradeBy(0.8).attack(0.01).release(1.6).pan(rand).room(0.9).delay(0.5).delaytime(0.375)', "seconds": 18, "say": 'scatter them'},
            {"op": SOLO, "lane": 'pad', "seconds": 18, "say": 'isolate the pad'},
            {"op": CLEAR, "seconds": 18, "say": 'and back'},
            {"op": DROP, "lane": 'kick', "seconds": 18, "say": 'breakdown'},
            {"op": DROP, "lane": 'snare', "seconds": 16, "say": 'strip it'},
            {"op": DROP, "lane": 'hats', "seconds": 16, "say": 'just pad and bells'},
            {"op": ADD, "lane": 'kick', "seconds": 18, "say": 'break returns'},
            {"op": ADD, "lane": 'snare', "seconds": 16, "say": 'snare back'},
            {"op": ADD, "lane": 'hats', "seconds": 20, "say": 'full'},
            {"op": FX, "lane": 'pad', "arg": '.fm(0.3).fmwave("brown")', "seconds": 18, "say": 'noise in the pad'},
            {"op": ADD, "lane": 'vox', "seconds": 18, "say": "bring in the vocal"},
            {"op": FX, "lane": 'vox', "arg": '.delay(0.55).delaytime(0.375).room(0.6).pan(rand)', "seconds": 16, "say": 'throw it into the delay'},
            {"op": FX, "lane": 'sub', "arg": '.lpf(slider(0.3,0,1).range(120,600)).lpq(2)', "seconds": 16, "say": 'put a slider on the sub'},
            {"op": SET, "lane": 'sub', "arg": 'lpq', "value": '6', "seconds": 16, "say": 'more bite on the sub'},
            {"op": FX, "lane": 'snare', "arg": '.delay(0.3).delaytime(0.375)', "seconds": 16, "say": 'delay on the snare'},
            {"op": SET, "lane": 'pad', "arg": 'lpq', "value": '3', "seconds": 16, "say": 'edge on the pad'},
            {"op": DROP, "lane": 'ghost', "seconds": 18, "say": 'thin'},
            {"op": DROP, "lane": 'bells', "seconds": 16, "say": 'out'},
        ],
    },

    'ambient': {
        "bpm": '~60', "cpm": '60/4',
        "blurb": 'slow evolving supersaw pads, long reverb, sparse fragments',
        "lanes": {
            'pad': 'n("<0,2,4 0,2,4 -3,-1,1 <-5,-3,-1 2,4,6>>*4").scale("c3:minor").s("supersaw").o(1)._scope()',
            'low': 'n("<0 -5>*2").scale("c2:minor").s("supersaw").o(2)',
            'bells': 'n("<0 7 5 3>*8").scale("c5:minor").s("triangle").o(3)',
            'shimmer': 'n("<12 14 17>*4").scale("c4:minor").s("supersaw").o(4)',
        },
        "script": [
            {"op": ADD, "lane": 'pad', "seconds": 34, "say": 'a pad, to begin'},
            {"op": FX, "lane": 'pad', "arg": '.detune(rand.range(0,0.25)).attack(1.2).decay(2).sustain(0.5).release(6)', "seconds": 28, "say": 'very slow attack'},
            {"op": FX, "lane": 'pad', "arg": '.lpf(slider(0.3,0,1).range(200,1400)).lpq(0)', "seconds": 30, "say": 'soften it'},
            {"op": FX, "lane": 'pad', "arg": '.pan(sine.range(0.25,0.75).slow(19)).room(0.92).size(9)', "seconds": 28, "say": 'put it in a large room'},
            {"op": ADD, "lane": 'low', "seconds": 30, "say": 'something underneath'},
            {"op": FX, "lane": 'low', "arg": '.detune(rand.range(0,0.15)).attack(3).release(9).lpf(300).lpq(0).room(0.8)', "seconds": 28, "say": 'deeper still'},
            {"op": ADD, "lane": 'bells', "seconds": 30, "say": 'sparse figures'},
            {"op": FX, "lane": 'bells', "arg": '.degradeBy(0.8).attack(0.01).release(4).lpf(2200).pan(rand).room(0.95).delay(0.5).delayfeedback(0.6)', "seconds": 30, "say": 'scatter and echo them'},
            {"op": ADD, "lane": 'shimmer', "seconds": 30, "say": 'a shimmer above'},
            {"op": FX, "lane": 'shimmer', "arg": '.degradeBy(0.85).detune(rand).attack(0.5).release(5).lpf(1600).lpq(0).pan(rand).room(0.9)', "seconds": 30, "say": 'barely there'},
            {"op": SET, "lane": 'pad', "arg": 'lpq', "value": '2', "seconds": 26, "say": 'a little edge'},
            {"op": DROP, "lane": 'pad', "seconds": 30, "say": 'let the pad go'},
            {"op": SOLO, "lane": 'bells', "seconds": 26, "say": 'only the bells'},
            {"op": CLEAR, "seconds": 26, "say": 'and back'},
            {"op": ADD, "lane": 'pad', "seconds": 32, "say": 'the pad returns'},
            {"op": SET, "lane": 'pad', "arg": 'lpq', "value": '0', "seconds": 28, "say": 'smooth again'},
            {"op": DROP, "lane": 'shimmer', "seconds": 30, "say": 'thinning'},
            {"op": DROP, "lane": 'bells', "seconds": 28, "say": 'quiet'},
        ],
    },

    'acid': {
        "bpm": '~128', "cpm": '128/4',
        "blurb": '303 acid: squelching resonant bassline over a hard kick',
        "lanes": {
            'kick': 's("bd*4").gain(0.98).o(1)._scope()',
            'hats': 's("[~ hh]*4").gain(0.3).o(2)',
            'ohat': 's("hh:3*8").gain(0.13).degradeBy(0.4).pan(rand).o(2)',
            'clap': 's("~ ~ cp ~").gain(0.4).room(0.3).o(2)',
            'acid': 'n("{0 0 12 0 3 0 7 10}%16").scale("a1:minor").s("sawtooth").o(3)',
            'sub': 'n("<0>*4").scale("a1:minor").s("sine").o(4)',
            'pad': 'n("<0,3,7 -2,2,5>*2").scale("a4:minor").s("supersaw").o(5)',
            'vox': 's("numbers*2").chop(4).gain(0.24).o(7)',
        },
        "script": [
            {"op": ADD, "lane": 'kick', "seconds": 18, "say": 'kick, four on the floor'},
            {"op": ADD, "lane": 'sub', "seconds": 16, "say": 'sub underneath'},
            {"op": FX, "lane": 'sub', "arg": '.attack(0.01).decay(0.4).sustain(0.3).release(0.2).lpf(150)', "seconds": 14, "say": 'keep it low'},
            {"op": FX, "lane": 'sub', "arg": '.duck("1").duckdepth(0.6)', "seconds": 14, "say": 'duck it'},
            {"op": ADD, "lane": 'acid', "seconds": 18, "say": 'the 303 line'},
            {"op": FX, "lane": 'acid', "arg": '.attack(0.004).decay(0.16).sustain(0.02).release(0.12)', "seconds": 14, "say": 'short and squelchy'},
            {"op": FX, "lane": 'acid', "arg": '.lpf(slider(0.25,0,1).range(200,3000)).lpq(10)', "seconds": 18, "say": 'tame it with an acid slider'},
            {"op": ADD, "lane": 'hats', "seconds": 16, "say": 'hats'},
            {"op": FX, "lane": 'acid', "arg": '.delay(0.26).delaytime(0.1875).delayfeedback(0.45)', "seconds": 16, "say": 'delay for power'},
            {"op": SET, "lane": 'acid', "arg": 'lpq', "value": '15', "seconds": 16, "say": 'push the resonance'},
            {"op": ADD, "lane": 'clap', "seconds": 16, "say": 'clap'},
            {"op": FX, "lane": 'acid', "arg": '.distort(1.4)', "seconds": 18, "say": 'destroy it with distortion'},
            {"op": ADD, "lane": 'ohat', "seconds": 16, "say": 'open hats'},
            {"op": SOLO, "lane": 'acid', "seconds": 18, "say": 'isolate the acid'},
            {"op": CLEAR, "seconds": 16, "say": 'all back'},
            {"op": DROP, "lane": 'kick', "seconds": 18, "say": 'breakdown'},
            {"op": ADD, "lane": 'pad', "seconds": 18, "say": 'a pad in the gap'},
            {"op": FX, "lane": 'pad', "arg": '.detune(rand).attack(1.5).release(4).lpf(perlin.range(600,2000)).lpq(0).room(0.8)', "seconds": 16, "say": 'wide and slow'},
            {"op": ADD, "lane": 'kick', "seconds": 18, "say": 'kick back'},
            {"op": SET, "lane": 'acid', "arg": 'lpq', "value": '8', "seconds": 16, "say": 'pull it back'},
            {"op": ADD, "lane": 'vox', "seconds": 18, "say": 'a voice in the machine'},
            {"op": DROP, "lane": 'ohat', "seconds": 18, "say": 'thin out'},
            {"op": DROP, "lane": 'vox', "seconds": 16, "say": 'and out'},
        ],
    },

    'psytrance': {
        "bpm": '~145', "cpm": '145/4',
        "blurb": 'rolling triplet bassline, hard kick, hypnotic leads',
        "lanes": {
            'kick': 's("bd*4").gain(1.0).o(1)._scope()',
            'roll': 'n("<0>*16").scale("e1:minor").s("sine").o(3)',
            'hats': 's("[~ hh]*8").gain(0.2).pan(rand).o(2)',
            'ride': 's("hh:4*16").gain(0.1).degradeBy(0.5).o(2)',
            'lead': 'n("{0 3 7 10 7 3}%16").scale("e4:minor").s("supersaw").o(4)',
            'pad': 'n("<0,3,7 -2,2,5>*2").scale("e3:minor").s("supersaw").o(5)',
        },
        "script": [
            {"op": ADD, "lane": 'kick', "seconds": 18, "say": 'kick, four on the floor'},
            {"op": ADD, "lane": 'roll', "seconds": 16, "say": 'the rolling bass'},
            {"op": FX, "lane": 'roll', "arg": '.struct("~ 1 1 ~ 1 1 ~ 1 1 ~ 1 1 ~ 1 1 ~")', "seconds": 16, "say": 'triplet feel'},
            {"op": FX, "lane": 'roll', "arg": '.attack(0.004).decay(0.09).sustain(0).release(0.06).lpf(280)', "seconds": 14, "say": 'tight and short'},
            {"op": FX, "lane": 'roll', "arg": '.duck("1").duckdepth(0.8).duckattack(0.06)', "seconds": 16, "say": 'duck hard against the kick'},
            {"op": ADD, "lane": 'hats', "seconds": 16, "say": 'hats'},
            {"op": ADD, "lane": 'lead', "seconds": 18, "say": 'hypnotic lead'},
            {"op": FX, "lane": 'lead', "arg": '.detune(rand.range(0,0.3)).attack(0.005).decay(0.13).sustain(0.05).release(0.3)', "seconds": 14, "say": 'detune it'},
            {"op": FX, "lane": 'lead', "arg": '.lpf(slider(0.4,0,1).range(600,3600)).lpq(2).pan(rand)', "seconds": 18, "say": 'filter and swirl'},
            {"op": FX, "lane": 'lead', "arg": '.delay(0.35).delaytime(0.1875).delayfeedback(0.5)', "seconds": 16, "say": 'delay'},
            {"op": ADD, "lane": 'ride', "seconds": 16, "say": 'ride on top'},
            {"op": SOLO, "lane": 'lead', "seconds": 18, "say": 'isolate the lead'},
            {"op": CLEAR, "seconds": 16, "say": 'back in'},
            {"op": DROP, "lane": 'kick', "seconds": 18, "say": 'breakdown'},
            {"op": ADD, "lane": 'pad', "seconds": 18, "say": 'pad underneath'},
            {"op": FX, "lane": 'pad', "arg": '.detune(rand).attack(2).release(4).lpf(perlin.range(400,1600)).lpq(0).room(0.85)', "seconds": 16, "say": 'slow and wide'},
            {"op": ADD, "lane": 'kick', "seconds": 18, "say": 'kick returns'},
            {"op": FX, "lane": 'lead', "arg": '.fm(0.4).fmwave("brown")', "seconds": 18, "say": 'FM it with noise'},
            {"op": DROP, "lane": 'ride', "seconds": 18, "say": 'thin'},
            {"op": DROP, "lane": 'lead', "seconds": 16, "say": 'out'},
        ],
    },

    'berlinschool': {
        "bpm": '~112', "cpm": '112/4',
        "blurb": 'Berlin School: 16th sequence under a travelling filter',
        "lanes": {
            'pad': 'n("<0,4,7 -3,0,4 -5,-1,2 0,4,7>*4").scale("c2:minor").s("supersaw").o(1)._scope()',
            'seq': 'n("{0 2 4 7 9 7 4 2}%16").scale("c3:minor").s("sawtooth").o(2)',
            'octave': 'n("{0 2 4 7 9 7 4 2}%16").add(n(12)).scale("c3:minor").s("square").o(3)',
            'kick': 's("bd*4").gain(0.5).o(4)',
        },
        "script": [
            {"op": ADD, "lane": 'pad', "seconds": 26, "say": 'a pad, to begin'},
            {"op": FX, "lane": 'pad', "arg": '.detune(rand.range(0,0.2)).attack(1.5).release(5).lpf(perlin.range(220,950)).lpq(0).room(0.82)', "seconds": 24, "say": 'slow and wide'},
            {"op": ADD, "lane": 'seq', "seconds": 24, "say": 'the sequence'},
            {"op": FX, "lane": 'seq', "arg": '.attack(0.005).decay(0.15).sustain(0.06).release(0.28)', "seconds": 20, "say": 'pluck it'},
            {"op": FX, "lane": 'seq', "arg": '.lpf(slider(0.35,0,1).range(280,2800)).lpq(3)', "seconds": 24, "say": 'and let the filter travel'},
            {"op": FX, "lane": 'seq', "arg": '.delay(0.42).delaytime(0.375).delayfeedback(0.6).pan(sine.range(0.2,0.8).slow(9))', "seconds": 22, "say": 'echo and drift'},
            {"op": ADD, "lane": 'octave', "seconds": 22, "say": 'double it an octave up'},
            {"op": FX, "lane": 'octave', "arg": '.degradeBy(0.62).attack(0.005).decay(0.11).lpf(tri.range(700,3400).slow(7)).gain(0.14)', "seconds": 20, "say": 'sparse and bright'},
            {"op": SET, "lane": 'seq', "arg": 'lpq', "value": '7', "seconds": 20, "say": 'more resonance'},
            {"op": ADD, "lane": 'kick', "seconds": 22, "say": 'a pulse underneath'},
            {"op": SOLO, "lane": 'seq', "seconds": 20, "say": 'isolate the sequence'},
            {"op": CLEAR, "seconds": 20, "say": 'back'},
            {"op": DROP, "lane": 'kick', "seconds": 22, "say": 'drop the pulse'},
            {"op": SET, "lane": 'seq', "arg": 'lpq', "value": '2', "seconds": 20, "say": 'soften the filter'},
            {"op": DROP, "lane": 'octave', "seconds": 22, "say": 'thinning'},
            {"op": DROP, "lane": 'seq', "seconds": 20, "say": 'just the pad'},
        ],
    },

    'deephouse': {
        "bpm": '~120', "cpm": '120/4',
        "blurb": 'slower jazzier house: rhodes chords, soft kick, brushed hats',
        "lanes": {
            'kick': 's("bd*4").gain(0.78).o(1)._scope()',
            'hats': 's("[~ hh]*4").gain(0.24).o(2)',
            'shaker': 's("hh:2*8").gain(0.1).degradeBy(0.3).pan(rand).o(2)',
            'snare': 's("~ sd:3").gain(0.3).room(0.35).o(2)',
            'bass': 'n("<0 0 -3 -5>*8").scale("f2:minor").s("sine").o(3)',
            'rhodes': 'n("<0,2,4,6 -3,-1,1,3 -5,-3,-1,1 <1,3,5,7 0,2,4,6>>*4").scale("f4:minor").s("triangle").o(4)',
            'vox': 's("speech:2").chop(8).gain(0.26).o(7)',
        },
        "script": [
            {"op": ADD, "lane": 'kick', "seconds": 20, "say": 'a soft kick'},
            {"op": ADD, "lane": 'hats', "seconds": 18, "say": 'brushed hats'},
            {"op": ADD, "lane": 'bass', "seconds": 18, "say": 'round bass'},
            {"op": FX, "lane": 'bass', "arg": '.attack(0.01).decay(0.28).sustain(0.15).release(0.3).lpf(320)', "seconds": 16, "say": 'keep it warm'},
            {"op": FX, "lane": 'bass', "arg": '.duck("1").duckdepth(0.6).duckattack(0.14)', "seconds": 16, "say": 'duck it gently'},
            {"op": ADD, "lane": 'rhodes', "seconds": 20, "say": 'rhodes chords'},
            {"op": FX, "lane": 'rhodes', "arg": '.attack(0.02).decay(0.6).sustain(0.25).release(1.5)', "seconds": 16, "say": 'let them ring'},
            {"op": FX, "lane": 'rhodes', "arg": '.lpf(slider(0.45,0,1).range(700,2000)).lpq(0).room(0.55)', "seconds": 18, "say": 'soften and space them'},
            {"op": ADD, "lane": 'snare', "seconds": 16, "say": 'snare'},
            {"op": FX, "lane": 'rhodes', "arg": '.delay(0.28).delaytime(0.375).pan(sine.range(0.4,0.6).slow(9))', "seconds": 18, "say": 'delay and drift'},
            {"op": ADD, "lane": 'shaker', "seconds": 16, "say": 'shaker'},
            {"op": ADD, "lane": 'vox', "seconds": 18, "say": 'a vocal chop'},
            {"op": FX, "lane": 'vox', "arg": '.rev().delay(0.4).delaytime(0.5).room(0.5).pan(rand)', "seconds": 16, "say": 'reverse it'},
            {"op": SOLO, "lane": 'rhodes', "seconds": 18, "say": 'isolate the chords'},
            {"op": CLEAR, "seconds": 16, "say": 'back'},
            {"op": DROP, "lane": 'kick', "seconds": 18, "say": 'breakdown'},
            {"op": DROP, "lane": 'hats', "seconds": 16, "say": 'let it breathe'},
            {"op": ADD, "lane": 'kick', "seconds": 18, "say": 'kick returns'},
            {"op": ADD, "lane": 'hats', "seconds": 18, "say": 'and the hats'},
            {"op": DROP, "lane": 'vox', "seconds": 18, "say": 'thin out'},
            {"op": DROP, "lane": 'shaker', "seconds": 16, "say": 'out'},
        ],
    },

    'breakbeat': {
        "bpm": '~136', "cpm": '136/4',
        "blurb": 'chopped breaks, syncopated bass, rave stabs',
        "lanes": {
            'break': 's("bd ~ sd bd ~ bd sd ~").gain(0.85).o(1)._scope()',
            'hats': 's("hh*8").gain(0.2).degradeBy(0.25).pan(rand).o(2)',
            'ghost': 's("sd:2*16").gain(0.08).degradeBy(0.75).o(2)',
            'bass': 'n("<0 0 5 3 0 -2 5 7>*8").scale("c2:minor").s("sawtooth").o(3)',
            'stab': 'n("<0,3,7>*4").scale("c4:minor").s("supersaw").o(4)',
            'pad': 'n("<0,3,7 -3,0,5>*2").scale("c3:minor").s("supersaw").o(5)',
        },
        "script": [
            {"op": ADD, "lane": 'break', "seconds": 18, "say": 'the break'},
            {"op": ADD, "lane": 'bass', "seconds": 16, "say": 'syncopated bass'},
            {"op": FX, "lane": 'bass', "arg": '.attack(0.01).decay(0.22).sustain(0.1).release(0.2).lpf(slider(0.3,0,1).range(200,900)).lpq(3)', "seconds": 18, "say": 'filter it'},
            {"op": FX, "lane": 'bass', "arg": '.duck("1").duckdepth(0.5).duckattack(0.1)', "seconds": 16, "say": 'duck it'},
            {"op": ADD, "lane": 'hats', "seconds": 16, "say": 'hats'},
            {"op": ADD, "lane": 'stab', "seconds": 18, "say": 'rave stabs'},
            {"op": FX, "lane": 'stab', "arg": '.degradeBy(0.55).detune(rand.range(0,0.3)).attack(0.01).decay(0.3).release(0.6)', "seconds": 16, "say": 'scatter them'},
            {"op": FX, "lane": 'stab', "arg": '.lpf(perlin.range(800,2600)).lpq(1).room(0.45).delay(0.3).delaytime(0.375)', "seconds": 18, "say": 'open and echo'},
            {"op": ADD, "lane": 'ghost', "seconds": 16, "say": 'ghost snares'},
            {"op": FX, "lane": 'break', "arg": '.fit()', "seconds": 16, "say": 'fit the break to the cycle'},
            {"op": SOLO, "lane": 'break', "seconds": 16, "say": 'isolate the break'},
            {"op": CLEAR, "seconds": 16, "say": 'back'},
            {"op": DROP, "lane": 'break', "seconds": 18, "say": 'breakdown'},
            {"op": ADD, "lane": 'pad', "seconds": 18, "say": 'a pad'},
            {"op": FX, "lane": 'pad', "arg": '.detune(rand).attack(1.5).release(3).lpf(perlin.range(400,1500)).lpq(0).room(0.8)', "seconds": 16, "say": 'wide'},
            {"op": ADD, "lane": 'break', "seconds": 18, "say": 'break returns'},
            {"op": SET, "lane": 'bass', "arg": 'lpq', "value": '7', "seconds": 16, "say": 'more bite'},
            {"op": DROP, "lane": 'ghost', "seconds": 18, "say": 'thin'},
            {"op": DROP, "lane": 'stab', "seconds": 16, "say": 'out'},
        ],
    },

    'dub': {
        "bpm": '~72', "cpm": '72/4',
        "blurb": 'deep bass, heavy delay throws, lots of space',
        "lanes": {
            'kick': 's("bd ~ ~ ~").gain(0.9).o(1)._scope()',
            'snare': 's("~ ~ sd ~").gain(0.38).o(2)',
            'hats': 's("[~ hh]*2").gain(0.14).o(2)',
            'bass': 'n("<0 0 5 7>*4").scale("g1:minor").s("sine").o(3)',
            'chords': 'n("<0,3,7>*4").scale("g3:minor").s("supersaw").o(4)',
            'echo': 'n("<12 10 7>*8").scale("g4:minor").s("triangle").o(5)',
        },
        "script": [
            {"op": ADD, "lane": 'bass', "seconds": 22, "say": 'deep bass first'},
            {"op": FX, "lane": 'bass', "arg": '.attack(0.02).decay(0.8).sustain(0.4).release(0.6).lpf(190)', "seconds": 18, "say": 'very low'},
            {"op": ADD, "lane": 'kick', "seconds": 18, "say": 'kick'},
            {"op": FX, "lane": 'bass', "arg": '.duck("1").duckdepth(0.4)', "seconds": 16, "say": 'duck it'},
            {"op": ADD, "lane": 'snare', "seconds": 18, "say": 'snare'},
            {"op": FX, "lane": 'snare', "arg": '.room(0.85).delay(0.7).delaytime(0.5).delayfeedback(0.72)', "seconds": 20, "say": 'throw it into the delay'},
            {"op": ADD, "lane": 'chords', "seconds": 20, "say": 'chords'},
            {"op": FX, "lane": 'chords', "arg": '.degradeBy(0.6).detune(rand.range(0,0.25)).attack(0.02).decay(0.5).release(1.4)', "seconds": 18, "say": 'sparse'},
            {"op": FX, "lane": 'chords', "arg": '.lpf(slider(0.4,0,1).range(350,1300)).lpq(0).room(0.7).delay(0.6).delaytime(0.375).delayfeedback(0.65)', "seconds": 20, "say": 'filter and echo'},
            {"op": ADD, "lane": 'hats', "seconds": 16, "say": 'hats'},
            {"op": ADD, "lane": 'echo', "seconds": 18, "say": 'something up high'},
            {"op": FX, "lane": 'echo', "arg": '.degradeBy(0.85).attack(0.01).release(2.5).pan(rand).room(0.9).delay(0.75).delaytime(0.75).delayfeedback(0.7)', "seconds": 20, "say": 'let it ring out'},
            {"op": SOLO, "lane": 'bass', "seconds": 18, "say": 'isolate the bass'},
            {"op": CLEAR, "seconds": 18, "say": 'back'},
            {"op": DROP, "lane": 'kick', "seconds": 20, "say": 'drop the kick'},
            {"op": DROP, "lane": 'snare', "seconds": 18, "say": 'dub it out'},
            {"op": ADD, "lane": 'kick', "seconds": 20, "say": 'kick returns'},
            {"op": ADD, "lane": 'snare', "seconds": 18, "say": 'and the snare'},
            {"op": DROP, "lane": 'echo', "seconds": 18, "say": 'thin'},
            {"op": DROP, "lane": 'chords', "seconds": 16, "say": 'out'},
        ],
    },

    'lofi': {
        "bpm": '~80', "cpm": '80/4',
        "blurb": 'soft keys, brushed drums, warm and low-passed',
        "lanes": {
            'keys': 'n("<0,2,4 -3,-1,1 -5,-3,-1 <2,4,6 0,2,4>>*4").scale("eb3:major").s("triangle").o(1)._scope()',
            'bass': 'n("<0 -5 -7>*4").scale("eb2:major").s("sine").o(2)',
            'kick': 's("bd ~ ~ bd ~ ~ ~ ~").gain(0.62).o(3)',
            'snare': 's("~ ~ ~ ~ sd ~ ~ ~").gain(0.3).room(0.3).o(4)',
            'hats': 's("hh*8").gain(0.1).degradeBy(0.35).pan(rand).o(4)',
            'twinkle': 'n("<7 9 12 14>*8").scale("eb5:major").s("triangle").o(5)',
        },
        "script": [
            {"op": ADD, "lane": 'keys', "seconds": 22, "say": 'soft keys'},
            {"op": FX, "lane": 'keys', "arg": '.attack(0.02).decay(0.7).sustain(0.25).release(1.6).lpf(1300).lpq(0)', "seconds": 18, "say": 'warm and dull'},
            {"op": ADD, "lane": 'bass', "seconds": 18, "say": 'bass'},
            {"op": FX, "lane": 'bass', "arg": '.attack(0.02).decay(0.6).sustain(0.3).release(0.5).lpf(250)', "seconds": 16, "say": 'round'},
            {"op": ADD, "lane": 'kick', "seconds": 18, "say": 'a lazy kick'},
            {"op": ADD, "lane": 'snare', "seconds": 16, "say": 'snare'},
            {"op": FX, "lane": 'keys', "arg": '.room(0.6).delay(0.2).pan(sine.range(0.4,0.6).slow(7))', "seconds": 18, "say": 'space it'},
            {"op": ADD, "lane": 'hats', "seconds": 16, "say": 'brushed hats'},
            {"op": ADD, "lane": 'twinkle', "seconds": 18, "say": 'something twinkling'},
            {"op": FX, "lane": 'twinkle', "arg": '.degradeBy(0.82).attack(0.01).release(2).pan(rand).room(0.8).delay(0.5)', "seconds": 18, "say": 'sparse'},
            {"op": SOLO, "lane": 'keys', "seconds": 18, "say": 'just the keys'},
            {"op": CLEAR, "seconds": 16, "say": 'back'},
            {"op": DROP, "lane": 'kick', "seconds": 18, "say": 'drop the drums'},
            {"op": DROP, "lane": 'snare', "seconds": 16, "say": 'let it float'},
            {"op": ADD, "lane": 'kick', "seconds": 18, "say": 'back in'},
            {"op": FX, "lane": 'keys', "arg": '.lpf(slider(0.35,0,1).range(600,2200)).lpq(1)', "seconds": 18, "say": 'a slider on the keys'},
            {"op": SET, "lane": 'keys', "arg": 'lpq', "value": '4', "seconds": 16, "say": 'open them a little'},
            {"op": FX, "lane": 'bass', "arg": '.duck("3").duckdepth(0.35)', "seconds": 16, "say": 'duck the bass under the kick'},
            {"op": SET, "lane": 'bass', "arg": 'duckdepth', "value": '0.55', "seconds": 16, "say": 'a touch more pump'},
            {"op": ADD, "lane": 'snare', "seconds": 18, "say": 'and out'},
            {"op": DROP, "lane": 'twinkle', "seconds": 16, "say": 'thin'},
        ],
    },

    'synthwave': {
        "bpm": '~66', "cpm": '66/4',
        "blurb": 'cinematic synthwave: wide supersaw stacks, bells, long tails',
        "lanes": {
            'brass': 'n("<0,3,7,10 0,3,7,10 -2,2,5,9 <-4,0,3,7 -5,-1,2,7>>*4").scale("d3:minor").s("supersaw").o(1)._scope()',
            'low': 'n("<0 -5>*2").scale("d2:minor").s("supersaw").o(2)',
            'bells': 'n("<7 10 12 15>*4").scale("d5:minor").s("triangle").o(3)',
            'lead': 'n("<0 5 3 7>*8").scale("d4:minor").s("supersaw").o(4)',
        },
        "script": [
            {"op": ADD, "lane": 'brass', "seconds": 30, "say": 'a wide brass stack'},
            {"op": FX, "lane": 'brass', "arg": '.detune(rand.range(0,0.3)).attack(0.9).decay(2).sustain(0.6).release(5)', "seconds": 26, "say": 'slow attack, long tail'},
            {"op": FX, "lane": 'brass', "arg": '.lpf(slider(0.4,0,1).range(400,1900)).lpq(0).room(0.9).size(9)', "seconds": 26, "say": 'filter and a big room'},
            {"op": FX, "lane": 'brass', "arg": '.vib(0.6).vibmod(0.06).pan(sine.range(0.3,0.7).slow(23))', "seconds": 24, "say": 'vibrato, and let it drift'},
            {"op": ADD, "lane": 'low', "seconds": 26, "say": 'an octave below'},
            {"op": FX, "lane": 'low', "arg": '.detune(rand.range(0,0.15)).attack(2).release(7).lpf(280).lpq(0).room(0.75)', "seconds": 24, "say": 'deep'},
            {"op": ADD, "lane": 'bells', "seconds": 26, "say": 'bells above'},
            {"op": FX, "lane": 'bells', "arg": '.degradeBy(0.7).attack(0.01).decay(1).release(4).pan(rand).room(0.92).delay(0.5).delaytime(0.75).delayfeedback(0.5)', "seconds": 26, "say": 'scatter and echo'},
            {"op": ADD, "lane": 'lead', "seconds": 26, "say": 'a lead line'},
            {"op": FX, "lane": 'lead', "arg": '.degradeBy(0.78).detune(rand).attack(0.4).release(3.5).lpf(perlin.range(700,2400)).lpq(0).room(0.88)', "seconds": 24, "say": 'sparse and singing'},
            {"op": SOLO, "lane": 'lead', "seconds": 22, "say": 'isolate the lead'},
            {"op": CLEAR, "seconds": 22, "say": 'back'},
            {"op": DROP, "lane": 'brass', "seconds": 26, "say": 'drop the brass'},
            {"op": SET, "lane": 'lead', "arg": 'lpq', "value": '3', "seconds": 22, "say": 'a little edge'},
            {"op": ADD, "lane": 'brass', "seconds": 26, "say": 'and bring it back'},
            {"op": DROP, "lane": 'bells', "seconds": 24, "say": 'thinning'},
            {"op": DROP, "lane": 'lead', "seconds": 22, "say": 'quiet'},
        ],
    },

    'triphop': {
        "bpm": '~88', "cpm": '88/4',
        "blurb": 'slow heavy breaks, dusty keys, deep bass',
        "lanes": {
            'keys': 'n("<0,3,7 -2,2,5 -4,0,3 <0,3,7 -5,-1,2>>*4").scale("d4:minor").s("triangle").o(1)._scope()',
            'bass': 'n("<0 0 -3 -5>*4").scale("d2:minor").s("sine").o(2)',
            'drums': 's("bd ~ ~ sd ~ ~ bd ~").gain(0.8).o(3)',
            'hats': 's("[~ hh]*4").gain(0.14).degradeBy(0.3).o(4)',
            'strings': 'n("<0,3,7>*2").scale("d5:minor").s("supersaw").o(5)',
            'vox': 's("speech:4").chop(8).gain(0.26).o(7)',
        },
        "script": [
            {"op": ADD, "lane": 'keys', "seconds": 22, "say": 'dusty keys'},
            {"op": FX, "lane": 'keys', "arg": '.attack(0.02).decay(0.8).sustain(0.2).release(1.8).lpf(1200).lpq(0)', "seconds": 18, "say": 'warm'},
            {"op": ADD, "lane": 'bass', "seconds": 18, "say": 'deep bass'},
            {"op": FX, "lane": 'bass', "arg": '.attack(0.02).decay(0.7).sustain(0.35).release(0.5).lpf(220)', "seconds": 16, "say": 'heavy'},
            {"op": ADD, "lane": 'drums', "seconds": 18, "say": 'slow break'},
            {"op": FX, "lane": 'bass', "arg": '.duck("1").duckdepth(0.45)', "seconds": 16, "say": 'duck it'},
            {"op": FX, "lane": 'keys', "arg": '.room(0.7).delay(0.35).delaytime(0.5).pan(sine.range(0.4,0.6).slow(11))', "seconds": 18, "say": 'space'},
            {"op": ADD, "lane": 'hats', "seconds": 16, "say": 'hats'},
            {"op": ADD, "lane": 'strings', "seconds": 18, "say": 'strings underneath'},
            {"op": FX, "lane": 'strings', "arg": '.degradeBy(0.7).detune(rand.range(0,0.2)).attack(1.2).release(3).lpf(perlin.range(500,1600)).lpq(0).room(0.85)', "seconds": 18, "say": 'slow swell'},
            {"op": ADD, "lane": 'vox', "seconds": 18, "say": 'a vocal'},
            {"op": FX, "lane": 'vox', "arg": '.rev().delay(0.5).delaytime(0.375).room(0.6).pan(rand)', "seconds": 16, "say": 'reverse and throw it'},
            {"op": SOLO, "lane": 'keys', "seconds": 18, "say": 'isolate the keys'},
            {"op": CLEAR, "seconds": 16, "say": 'back'},
            {"op": DROP, "lane": 'drums', "seconds": 18, "say": 'drop the break'},
            {"op": ADD, "lane": 'drums', "seconds": 18, "say": 'and back in'},
            {"op": FX, "lane": 'keys', "arg": '.lpf(slider(0.4,0,1).range(500,2000)).lpq(1)', "seconds": 18, "say": 'a slider on the keys'},
            {"op": SET, "lane": 'keys', "arg": 'lpq', "value": '5', "seconds": 16, "say": 'dirty them up'},
            {"op": DROP, "lane": 'vox', "seconds": 18, "say": 'thin'},
            {"op": DROP, "lane": 'strings', "seconds": 16, "say": 'out'},
        ],
    },

}

DEFAULT_GENRE = "ambient"


def genre_names() -> list[str]:
    return sorted(GENRES)


def describe(genre: str) -> str:
    e = GENRES.get(genre)
    return f"{genre} ({e['bpm']}) — {e['blurb']}" if e else genre


def total_seconds(genre: str) -> float:
    e = GENRES.get(genre)
    return sum(m.get("seconds", 20) for m in e["script"]) if e else 0.0
