"""
Quest Registry - Definitions and logic for Oakhaven Quests
"""

QUESTS = {
    "arrival": {
        "id": "arrival",
        "name": "A Stranger in the Mud",
        "npc": "elara",
        "description": "Elder Elara wants you to introduce yourself to the town. Visit Mira at the Stone Hearth and Hemlock at the shop.",
        "requirements": {"level": 1},
        "tasks": ["talk_barkeep", "talk_hemlock", "talk_elara"],
        "rewards": {"xp": 50, "gil": 20},
        "completion_msg": "Elder Elara nods approvingly. 'Small steps, adventurer. You're part of Oakhaven now.'",
    },
    "whisperwood_scout": {
        "id": "whisperwood_scout",
        "name": "The Darkening Woods",
        "npc": "guard",
        "description": "The Watchtower guards are worried about movement in the Whisperwood Deep. Scout the area by hunting there once.",
        "requirements": {"level": 3},
        "tasks": ["hunt_whisperwood_deep", "talk_guard"],
        "rewards": {"xp": 150, "gil": 100, "item": "lucky_charm"},
        "completion_msg": "The guard takes your report. 'Deep movement, eh? We'll double the patrols. Take this for your trouble.'",
    },
    "maren_herbs": {
        "id": "maren_herbs",
        "name": "Sister Maren's Request",
        "npc": "maren",
        "description": "Sister Maren needs rare herbs found only near the Trade Road. Defeat a 'Road Bandit' to recover her stolen supplies.",
        "requirements": {"level": 4},
        "tasks": ["kill_bandit", "talk_maren"],
        "rewards": {"xp": 200, "gil": 50, "recipe": "potion", "item": "silverleaf"},
        "completion_msg": "Sister Maren's eyes light up. 'The Silverleaf! Now I can finish the brew. Bless you.'",
    },
    "grimstone_relic": {
        "id": "grimstone_relic",
        "name": "The Aeridorian Signal",
        "npc": "elara",
        "description": "Elder Elara has detected a pulse from deep below Oakhaven — Aeridorian constructs are waking up. Clear a dungeon and report back what you find.",
        "requirements": {"level": 5},
        "tasks": ["complete_dungeon", "talk_elara"],
        "rewards": {"xp": 500, "gil": 200, "item": "lightstone"},
        "completion_msg": "Elara listens to your account without expression. 'The constructs are active again. That pulse was not random. Something triggered them.' She pauses. 'Keep the lightstone. You'll need it more than I will.'",
    },
    "deep_hunt": {
        "id": "deep_hunt",
        "name": "What Sleeps Beneath",
        "npc": "guard",
        "description": "The Watchtower has lost contact with a patrol in the Whisperwood Deep. Something powerful took them. Find and kill the creatures responsible — a Frost Wolf and an Owlbear.",
        "requirements": {"level": 7},
        "tasks": ["kill_frost_wolf", "kill_owlbear", "talk_guard"],
        "rewards": {"xp": 1200, "gil": 350, "item": "ironbark_potion"},
        "completion_msg": "The guard stares at the blood on your gear. 'You found them, didn't you. What was left of them.' A long silence. 'The Watchtower owes you a debt. This doesn't cover it, but it's what we have.'",
    },
    "grimstone_path": {
        "id": "grimstone_path",
        "name": "The Road to Iron",
        "npc": "hooded_figure",
        "description": "The Ironclad Guild has barricaded the Trade Road north to Grimstone. Speak to Elder Elara about the Guild, then seek a way to break the resonance lock at the Aeridor Ruins crystals.",
        "requirements": {"level": 15},
        "tasks": ["talk_elara", "look_crystals"],
        "rewards": {"xp": 6000, "gil": 2000, "item": "aeridor_shard"},
        "completion_msg": "The resonance lock shatters. The barricade collapses. The road north is open.",
    },
    "weight_of_the_count": {
        "id": "weight_of_the_count",
        "name": "The Weight of the Count",
        "npc": "senna",
        "description": "Senna the Assayer has kept secret copies of Grimstone's real yield ledgers for months. She needs them delivered to Elder Elara in Oakhaven without the Guild finding out.",
        "requirements": {"level": 15},
        "tasks": ["talk_senna", "talk_elara"],
        "rewards": {"xp": 4000, "gil": 1500, "item": "resonance_ring"},
        "completion_msg": "Elara holds the flask for a long moment before opening it. 'Resonance crystal ore. I was afraid of this.' She doesn't say what she's afraid of, exactly. She says she'll handle it.",
    },
    "what_came_up_from_below": {
        "id": "what_came_up_from_below",
        "name": "What Came Up From Below",
        "npc": "rook",
        "description": "Rook finally talked. Three miners entered the Restricted Level beneath Grimstone. Two came back wrong. One didn't come back at all. He wants someone to go down there. He won't say more than that.",
        "requirements": {"level": 15},
        "tasks": ["talk_rook", "complete_dungeon", "talk_rook"],
        "rewards": {"xp": 5000, "gil": 1000, "item": "aeridorian_sigil"},
        "completion_msg": "Rook listens to what you found. He doesn't ask about Mossen. He already knows. He stares at the table for a while. 'That's what I thought,' he says. That's all.",
    },
    "old_pells_favour": {
        "id": "old_pells_favour",
        "name": "Old Pell's Favour",
        "npc": "old_pell",
        "description": "Old Pell needs an escort through a Spine pass the Guild doesn't know about — a delivery for his Silvani contacts. The Spine is not safe. That's why he needs someone.",
        "requirements": {"level": 15},
        "tasks": ["talk_old_pell", "hunt_spine_of_the_world", "talk_old_pell"],
        "rewards": {"xp": 4500, "gil": 800, "item": "whisperwood_talisman"},
        "completion_msg": "Pell completes the handoff with the Silvani contact without ceremony. On the way back through the pass, he tells you what the Silvani said. You wish he hadn't. You'll need to tell Elara.",
    },
    "silent_ones": {
        "id": "silent_ones",
        "name": "The Final Silence",
        "npc": "elara",
        "description": "The Shrine of the Silent Ones has gone dark. Elder Elara believes the seal is failing. Pray at the Shrine, then seek out a dungeon and defeat its boss to purge the corrupted essence.",
        "requirements": {"level": 9},
        "tasks": ["pray_shrine", "complete_dungeon", "talk_elara"],
        "rewards": {"xp": 1500, "gil": 500, "item": "amulet_health"},
        "completion_msg": "Elara is waiting in the square when you return. She doesn't ask what you saw in the dark. 'The seal held. This time.' She presses something cold and heavy into your hand. 'The Silent Ones left this for whoever came back. Not everyone does.'",
    },
    "aeridor_remnant": {
        "id": "aeridor_remnant",
        "name": "The Waking Metal",
        "npc": "elara",
        "description": "An Aeridorian Iron Golem has broken the perimeter of the ruins. Destroy it before it reaches the treeline.",
        "requirements": {"level": 11},
        "tasks": ["kill_iron_golem", "talk_elara"],
        "rewards": {"xp": 2500, "gil": 800, "item": "void_band"},
        "completion_msg": "Elara inspects the metallic plating you brought back. 'They are learning. Or remembering. I am not sure which is worse.'",
    },
    "shadow_incursion": {
        "id": "shadow_incursion",
        "name": "The Darkening",
        "npc": "guard",
        "description": "The Watchtower reports unnatural cold from the Deepwood. A Shadow Lich is massing forces. End it.",
        "requirements": {"level": 13},
        "tasks": ["kill_shadow_lich", "talk_guard"],
        "rewards": {"xp": 3500, "gil": 1500, "item": "mox_pearl"},
        "completion_msg": "The guard shivers despite the sun. 'We saw the shadows retreat. Oakhaven owes you its life today.'",
    },
    "the_last_guardian": {
        "id": "the_last_guardian",
        "name": "The Last Guardian",
        "npc": "elara",
        "description": "The heart of the Aeridor Ruins has opened. We cannot wait any longer. Go in. Do not come out until it is quiet.",
        "requirements": {"level": 15},
        "tasks": ["complete_dungeon", "talk_elara"],
        "rewards": {"xp": 5000, "gil": 5000, "item": "the_end"},
        "completion_msg": "Elder Elara bows her head. 'It is done. The bones of Aeridor can finally rest. And so can we.'",
    },
}

def get_quest(quest_id):
    return QUESTS.get(quest_id)

def get_npc_quests(npc_id):
    """Returns a list of quests offered by a specific NPC."""
    return [q for q in QUESTS.values() if q["npc"] == npc_id]
