#!/usr/bin/env python3
"""
tools/maintenance/build_user_folder_index.py

Write a README.md into each user folder: what is here, and what it covers.

Opening `Ekco_177011971818782721/` used to mean 178 undifferentiated daily
files and one generated profile, which answers none of the questions a person
actually has — how long have they talked, about what, where do I look for a
given month, what has this person shared.

Everything here is derived from the transcripts themselves. No model is
involved, so it is cheap, regenerable, and cannot invent anything.

    python tools/maintenance/build_user_folder_index.py --apply
"""
import argparse
import re
import sys
from collections import Counter
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))

USER_LOGS = ROOT / "knowledge_base" / "user_logs"

TURN = re.compile(r"^\[(\d{4}-\d\d-\d\d) \d\d:\d\d:\d\d\] ([^:\n]+): (.*?)(?=^\[\d{4}-|\Z)",
                  re.M | re.S)
SHARED = re.compile(r"^\[shared link: (.+?)\]$", re.M)

STOP = set("""the a an and or but if then than that this these those there here it its
is are was were be been being am do does did doing have has had having will would can
could should may might must shall of to in on at by for with from as into about over
after before between out up down off again further once all any both each few more most
other some such no nor not only own same so too very just i you he she we they me him
her them my your his our their what which who whom when where why how one two also get
got like really think know see want way thing things lot much even still back going
yeah yes ok okay lol im dont didnt cant thats theres youre ive hes shes were theyre
kaia shared link https http www com youtube watch status embed image title
description gonna wanna gotta kinda sorta maybe pretty right actually
something anything nothing someone everything shit fuck fucking damn
stuff make made makes need needs used using goes went come came look
looks looking said says tell told give given take taken find found ekco starkind jimjam cecily toxigen lune tenno henka gnowmaticflux
thoughts whatever apparently last while
didn doesn isn wasn aren hasn haven couldn wouldn shouldn won don ain""".split())


def display_name(dirname: str) -> str:
    return dirname.rsplit("_", 1)[0].replace("_", " ").strip() or dirname


def analyse(user_dir: Path):
    days, turns = set(), 0
    by_speaker = Counter()
    words = Counter()
    links = []
    files = []

    for f in sorted(user_dir.glob("interactions_*.md")):
        text = f.read_text(encoding="utf-8", errors="replace")
        matches = TURN.findall(text)
        files.append((f.name, len(matches)))
        for date, who, body in matches:
            days.add(date)
            turns += 1
            by_speaker[who.strip()] += 1
            if who.strip().lower() != "kaia":
                # Strip URLs and citations first: otherwise "https", "link"
                # and "shared" rank as the user's main interests.
                clean = SHARED.sub("", re.sub(r"https?://\S+", "", body))
                for w in re.findall(r"[a-z][a-z]{3,}", clean.lower()):
                    if w not in STOP and "'" not in w:
                        words[w] += 1
        links.extend(SHARED.findall(text))

    return {
        "days": sorted(days), "turns": turns, "speakers": by_speaker,
        "topics": words.most_common(25), "links": links, "files": files,
    }


def render(user_dir: Path, a: dict) -> str:
    name = display_name(user_dir.name)
    uid = user_dir.name.rsplit("_", 1)[-1]
    first, last = (a["days"][0], a["days"][-1]) if a["days"] else ("—", "—")

    try:
        from utils.social.kaia_identities import registry
        forum = registry.get_forum_ids(uid)
    except Exception:
        forum = []

    out = [
        f"# {name}",
        "",
        "*Generated by `tools/maintenance/build_user_folder_index.py` — "
        "regenerate it rather than editing by hand.*",
        "",
        "| | |",
        "|---|---|",
        f"| Discord id | `{uid}` |",
        f"| Conversation spans | **{first} → {last}** ({len(a['days'])} days) |",
        f"| Turns on record | **{a['turns']:,}** |",
    ]
    if forum:
        out.append(f"| Linked forum accounts | {', '.join(str(f) for f in forum)} |")
    who = ", ".join(f"{s} {c:,}" for s, c in a["speakers"].most_common(4))
    out += [f"| Turns by speaker | {who} |", ""]

    if a["topics"]:
        out += ["## What they talk about", "",
                "Most frequent content words in their own turns — a rough index, "
                "not a summary.", "",
                "> " + " · ".join(w for w, _ in a["topics"]), ""]

    if a["links"]:
        out += [f"## Links they have shared ({len(a['links'])})", ""]
        for t in a["links"][-15:]:
            out.append(f"- {t}")
        if len(a["links"]) > 15:
            out.append(f"- *…and {len(a['links']) - 15} earlier*")
        out.append("")

    out += ["## Files", "",
            "Closed months are rolled into one archive each; the last week stays "
            "as daily files. Every turn carries its own timestamp, so a merged "
            "month is still date-addressable.", "",
            "| File | Turns |", "|---|---|"]
    for fname, n in a["files"]:
        out.append(f"| `{fname}` | {n} |")
    out += ["",
            "`user_profile.md` is Kaia's own written impression of this person, "
            "regenerated by `generate_user_profiles.py`.", ""]
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--apply", action="store_true")
    ap.add_argument("--include-forum", action="store_true")
    args = ap.parse_args()

    written = 0
    for user_dir in sorted(p for p in USER_LOGS.iterdir() if p.is_dir()):
        if user_dir.name.startswith("forum_") and not args.include_forum:
            continue
        a = analyse(user_dir)
        if not a["turns"]:
            continue
        text = render(user_dir, a)
        written += 1
        if args.apply:
            (user_dir / "README.md").write_text(text, encoding="utf-8")
        else:
            print(f"  {user_dir.name}: {a['turns']:,} turns, {len(a['days'])} days, "
                  f"{len(a['files'])} files, {len(a['links'])} links")
    print(f"\n{'wrote' if args.apply else 'would write'} {written} folder indexes")
    if not args.apply:
        print("(dry run — re-run with --apply)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
